name: Work Item
description: New work item for Ape team
body:
  - type: textarea
    id: pitch
    attributes:
      label: Evelator Pitch
      placeholder: 1-2 line summary of the scope of this work item
  - type: input
    id: value
    attributes:
      label: Value
      placeholder: |
        Who is this for?
        Persona or group of people whom will derive value from the scenario.
        What benefits will be achieved or business metrics improved?
  - type: textarea
    id: dependencies
    attributes:
      label: Dependencies
      placeholder: |
         Call out key people, teams, tech dependencies, or assumptions.
  - type: textarea
    id: approach
    attributes:
      label: Design Approach
      placeholder: |
        Free text / diagram / whiteboard picture / etc. that clearly shows your approach and considerations to build the task list.
        Existing code patterns in production code base that you will base your work off of.
  - type: markdown
    id: tasks
    attributes:
      label: Task List
      description: Bulleted list describing the exit criteria, desired end state and any documentation, monitors, work for DRI, etc. that will need to be added to make sure someone else can support once it's live.
      placeholder: \[\] Tasks go here
  - type: textarea
    id: date
    attributes:
      label: Estimated Completion Date
  - type: markdown
    id: review
    attributes:
      description: 1-2 people needed for signoff
      label: |
        Do not signoff unless:

        - 1. agreed the tasks and design approach will achieve acceptance, and
        - 2. the work can be completed by one person within the SLA.
             Design reviewers should consider simpler approaches to achieve goals.

        (Please leave a comment to sign off)
