name: Build and Push Docker Images for All Tags

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Get all tags
      id: get-tags
      run: |
        git fetch --tags
        TAGS=$(git tag -l 'v*' --sort=-v:refname | grep -E '^v0\.[7-8]\.' | sort -V)
        echo "::set-output name=tags::${TAGS}"

    - name: Build and Push Docker Images
      uses: docker/build-push-action@v4
      with:
        push: false
        context: .
        tags: |
          ghcr.io/${{ github.repository }}:${{ matrix.tag }}
      strategy:
        matrix:
          tag: ${{ fromJson(needs.get-tags.outputs.tags) }}
